// Fuente unica de datos del portfolio.
// Para agregar un proyecto: copia un objeto, cambia los datos y sube las imagenes.
// Los campos rol, problema, proceso y resultado son opcionales: si no existen, no se muestran.
const PROYECTOS = [
  {
    id: "jamm",
    titulo: "Jamm",
    resumen: "Diseños personalizados orientados a remeras.",
    stack: ["Photoshop", "Illustrator"],
    portada: "images/jamm/ferrari.png",
    portadaAlt: "Remera, diseño de Jamm",
    rol: "Diseñador",
    // problema: "",
    proceso: "En esta etapa en Jamm, mi tarea consistía en realizar los diseños para luego ser estampados en remeras y tote bags. La propuesta incluye tanto diseños de impronta personal como pedidos a medida para clientes.",
    // resultado: "",
    galeria: [
      { src: "images/jamm/corvette.png", alt: "Remera Corvette, diseño de Jamm" },
      { src: "images/jamm/ferrari.png", alt: "Remera Ferrari Lewis Hamilton, diseño de Jamm" },
      { src: "images/jamm/ford.png", alt: "Remera Ford F-100, diseño de Jamm" },
      { src: "images/jamm/palermo.png", alt: "Remera Palermo, diseño de Jamm" },
      { src: "images/jamm/sailor-moon.png", alt: "Remera Sailor Moon, diseño de Jamm" },
    ],
    links: [{ texto: "Ver en Instagram", url: "https://www.instagram.com/estampasjamm/" }],
  },  {
    id: "3dpm",
    titulo: "3DPM",
    resumen: "Catálogo web con panel de administración editable por el cliente.",
    stack: ["HTML", "CSS", "JavaScript", "Firebase", "Vercel", "Figma"],
    portada: "images/3dpm/logo-2.png",
    portadaAlt: "Home del catálogo web de 3DPM",
    rol: "Diseño y desarrollo completo.",
    problema: "El cliente necesitaba un catálogo online para mostrar sus servicios y productos, y poder actualizarlo sin depender de un desarrollador.",
    proceso: "Partí de un mockup en Figma y lo llevé a código con CSS a medida (glassmorphism, responsive, divisores con ondas). Reestructuré el sitio para que los servicios sean lo primero que se ve, y armé un panel de administración con Firebase donde el cliente edita productos y categorías. Antes de publicar hice una revisión de seguridad: corregí una vulnerabilidad XSS, ajusté robots.txt, oculté el panel de los buscadores y desactivé un método de login que no correspondía.",
    resultado: "",
    galeria: [
      { src: "images/3dpm/logo.png", alt: "logo de 3DPM" },
      { src: "images/3dpm/instagram post - 1.png", alt: "posteo" },
      { src: "images/3dpm/image.png", alt: "captura de figma" },
      { src: "images/3dpm/menu-3dpm.png", alt: "Home del catálogo de 3DPM" },
      { src: "images/3dpm/desplegable.png", alt: "desplegable del catálogo de 3DPM" },
    ],
    links: [],
  },  {
    id: "ahd",
    titulo: "AHdesign",
    resumen: "Diseños Personales de distintas tematicas e intereses.",
    stack: ["Photoshop", "Illustrator"],
    portada: "images/ah/logo.jpg",
    portadaAlt: "diseño de ahdesign",
    rol: "Diseñador.",
    problema: "Cuando comencé a aprender a usar la suite de Adobe, me propuse crear diseños personales para practicar y profundizar mis conocimientos. Compartí estos procesos en Instagram, donde pude documentar la evolución de mi trabajo.",
    proceso: "A partir de ideas e intereses propios, desarrollo diseños aplicables a posters, wallpapers y estampas para indumentaria, combinando diversas herramientas de la suite de Adobe.",
    resultado: "",
    galeria: [
      { src: "images/ah/boca.jpg", alt: "poster de Leandro Paredes" },
      { src: "images/ah/lewis.jpg", alt: "poster de Lewis Hamilton" },
      { src: "images/ah/messi.jpg", alt: "poster de Lionel Messi" },
      { src: "images/ah/mad max-ig.jpg", alt: "poster de Verstappen" },
      { src: "images/ah/verstappen ig.jpg", alt: "poster de Verstappen" },
      { src: "images/ah/senna.jpg", alt: "composicion de Senna" },
    ],
    links: [],
  },
];
